### ISSUE TITLE
小组大作业（Final Group Project）

### ISSUE THREAD

**Issue by lost-Lynn** [computational-class/cjc2016#104]
**项目主题**
“占领华尔街”中的社交网络舆情数据挖掘——以Twitter为例

**小组分工**
李思滢-代码实现部分
闫琰-项目报告撰写（具体分工见报告）
张鹤仪-项目报告撰写（具体分工见报告）

**附件说明**
共有两个nb文件
1）Final Group Project包含文档和大部分程序代码
注：其中评论网络部分使用networkx1.0版本，在2.0版本中可能会报错
2）Hashtag RecSys是基于hashtag的推荐系统代码，由于是在py2环境中使用GraphLab完成，故另附 

[Final Group Project - Siying Li & Yan Yan & Heyi Zhang.zip](https://github.com/computational-class/cjc/files/2159047/Final.Group.Project.-.Siying.Li.Yan.Yan.Heyi.Zhang.zip)

**Comment by yuan-fang1** [comment]
感恩sing的新帖子，笔芯❤

**小组成员**
方圆、尹航、吕之睿

**小组分工**
方圆-推荐系统&评论网络
尹航-主题模型
吕之睿-数据读取&清洗

**附件说明**
1) Final Group Project - 数据清洗、主题模型、评论网络.ipynb ：含有数据读取、清洗、主题模型分析和评论网络构成的代码，使用python3
2) Final Group Project - 推荐系统.ipynb：含有推荐系统的代码，使用python2
3) topic_model.txt ：主题模型及推荐系统使用的部分数据
4) tweet_network.csv：评论网络的邻接表
5) usertag.txt ：用户、tag、次数的统计

[Final Group Project - 方圆、尹航、吕之睿.zip](https://github.com/computational-class/cjc/files/2159912/Final.Group.Project.-.zip)

**Comment by isLanguid** [comment]
小组小组成员
闪雪萌、申曦霖、姚书媛

小组分工
闪雪萌-hashtag推荐&评论网络
申曦霖-主题情感模型
姚书媛-数据读取&清洗

附件说明

小组大作业 - 数据清洗、主题模型、hashtag推荐系统部分、评论网络.ipynb 
recommand_hashtag - 推荐系统剩余部分.ipynb

**Comment by isLanguid** [comment]
附件：[小组大作业-闪雪萌、申曦霖、姚书媛.zip](https://github.com/computational-class/cjc/files/2160129/-.zip)

**Comment by txn0121** [comment]
小组成员：宋晗煜、唐昕宁、伍音璇

小组分工：
唐昕宁：数据读取、清洗、主题模型
宋晗煜：评论网络
伍音璇：基于hashtag的推荐系统

附件内容：小组作业（含html, markdown, ipynb三种格式）
[Groupwork(shy_txn_wyx).zip](https://github.com/computational-class/cjc/files/2160157/Groupwork.shy_txn_wyx.zip)

**Comment by lizhenan522** [comment]
**项目主题**
基于Twitter数据集的文本分析与评论网络构建

**小组成员：**
李哲男 周丹旎 王希

**小组分工**
李哲男-代码实现部分
周丹旎-项目报告撰写（摘要、前言、背景）
王希-项目报告撰写（思路和结论）

**附件说明**
共有两个nb文件
1、py文件
2、HTML文件（易读）
在Python2 的基础上编写

[Final Group Project zhenan Wangxi Zhou danni3.0.zip](https://github.com/computational-class/cjc/files/2160164/Final.Group.Project.zhenan.Wangxi.Zhou.danni3.0.zip)

**Comment by lyzzz0** [comment]
组员：李雨蓁、崔银月、刘望

小组分工：
李雨蓁：计算每天推特数、构建评论网络
崔银月：情感分析模型建立、数据清洗
刘望：将数据整理为人、hashtag、次数，构建基于物的相似性推荐系统

附件说明：
报告html版本，附件一：情感分析建立，附件二：基于物的推荐系统模型。

[计算传播学期末报告——李雨蓁、崔银月、刘望.zip](https://github.com/computational-class/cjc/files/2161481/default.zip)
