### ISSUE TITLE
Olivia_linwei

### ISSUE THREAD

**Issue by Olivia98106** [computational-class/cjc2016#107]
## Hello, my name is Wei.

>here are some texts.
*Nice to meet you all.*
![小太阳](https://user-images.githubusercontent.com/45172844/59093256-0ec4b800-8946-11e9-92c2-c1427a26e6d0.png)

**Comment by Olivia98106** [comment]
[ H2_Olivia.html.zip](https://github.com/computational-class/cjc/files/3269073/H2_Olivia.html.zip)
Here is the homework02.

**Comment by Olivia98106** [comment]
Here is Homework02~
[ H2_Olivia-revised.html.zip](https://github.com/computational-class/cjc/files/3269177/H2_Olivia-revised.html.zip)

**Comment by Olivia98106** [comment]
[H3_Olivia.html.zip](https://github.com/computational-class/cjc/files/3288624/H3_Olivia.html.zip)
logistic regression_89.05%
I will try more models today~

**Comment by Olivia98106** [comment]
[H3_Olivia_lr_rf_svm_knn.html.zip](https://github.com/computational-class/cjc/files/3288962/H3_Olivia_lr_rf_svm_knn.html.zip)
more ML methods followed ~

**Comment by Olivia98106** [comment]
[H4_Olivia.zip](https://github.com/computational-class/cjc/files/3292585/H4_Olivia.zip)
Here is Homework04~

**Comment by Olivia98106** [comment]
[H5_Olivia.zip](https://github.com/computational-class/cjc/files/3293680/H5_Olivia.zip)
Here is Homework05~

**Comment by Olivia98106** [comment]
[H6_Olivia.html.zip](https://github.com/computational-class/cjc/files/3293974/H6_Olivia.html.zip)
Here is Homework06!~ 

Thank you, Dr. Chengjun Wang!

**Comment by chengjun** [comment]
thank u for your participation. have a nice semester.
