### ISSUE TITLE
游雁麟Yanlin You

### ISSUE THREAD

**Issue by YouYanlin** [computational-class/cjc2016#112]
### 第一次作业

- 游雁麟

- 学号：18210130104

- 个人主页：https://youyanlin.github.io
[homework1-yanlin.zip](https://github.com/computational-class/cjc/files/3265377/homework1-yanlin.zip)

**Comment by YouYanlin** [comment]
### 第二次作业

- 游雁麟
[homework2&3-youyanlin.zip](https://github.com/computational-class/cjc/files/3268509/homework2.3-youyanlin.zip)

**Comment by YouYanlin** [comment]
### 第三次作业-机器学习部分
游雁麟 18210130104
[homework4-machinelearning-youyanlin.zip](https://github.com/computational-class/cjc/files/3284224/homework4-machinelearning-youyanlin.zip)

**Comment by YouYanlin** [comment]
### 第四次作业-情感分析部分
游雁麟 18210130104
[homework5-youyanlin.zip](https://github.com/computational-class/cjc/files/3290298/homework5-youyanlin.zip)

**Comment by YouYanlin** [comment]
### 第五次作业-graphlab和推荐部分
游雁麟 18210130104
[homework6-youyanlin.zip](https://github.com/computational-class/cjc/files/3292941/homework6-youyanlin.zip)

**Comment by YouYanlin** [comment]
### 第六次作业-网络
游雁麟 18210130104
[homework7-youyanlin.zip](https://github.com/computational-class/cjc/files/3293994/homework7-youyanlin.zip)

**Comment by YouYanlin** [comment]
### 个人作业-Fake News
游雁麟 18210130104
感谢老师一学期的辛苦付出~祝老师工作一切顺利！
[个人作业-游雁麟.zip](https://github.com/computational-class/cjc/files/3417572/-.zip)

**Comment by chengjun** [comment]
> ### 个人作业-Fake News
> 游雁麟 18210130104
> [个人作业-游雁麟.zip](https://github.com/computational-class/cjc/files/3417572/-.zip)

Thank u for your sharing of personal research project.
