### ISSUE TITLE
Luo Taotao

### ISSUE THREAD

**Issue by ARIELTAOTAO** [computational-class/cjc2016#118]
# 第一次作业
- 骆陶陶
- 学号：18210130070
- 网站：https://arieltaotao.github.io/

[骆陶陶.zip](https://github.com/computational-class/cjc/files/3265509/default.zip)

**Comment by ARIELTAOTAO** [comment]
# 第二次作业
[骆陶陶 第二次作业.zip](https://github.com/computational-class/cjc/files/3268498/default.zip)

**Comment by ARIELTAOTAO** [comment]
# 第三次作业
[Luo Taotao zuoye3.zip](https://github.com/computational-class/cjc/files/3281506/Luo.Taotao.zuoye3.zip)

**Comment by ARIELTAOTAO** [comment]
# 第五次作业
[Luo Taotao zuoye5.zip](https://github.com/computational-class/cjc/files/3290644/Luo.Taotao.zuoye5.zip)

**Comment by ARIELTAOTAO** [comment]
# 第四+六+七次作业
[Luo Taotao zuoye4+6+7.zip](https://github.com/computational-class/cjc/files/3293092/Luo.Taotao.zuoye4%2B6%2B7.zip)

**Comment by ARIELTAOTAO** [comment]
# 第八次作业
[Luo Taotao zuoye8.zip](https://github.com/computational-class/cjc/files/3294164/Luo.Taotao.zuoye8.zip)

**Comment by ARIELTAOTAO** [comment]
#期末个人作业-骆陶陶
[HousePrice Luotaotao.zip](https://github.com/computational-class/cjc/files/3414383/HousePrice.Luotaotao.zip)

**Comment by ARIELTAOTAO** [comment]
# 期末个人作业-骆陶陶
[HousePrice Luotaotao.zip](https://github.com/computational-class/cjc/files/3414384/HousePrice.Luotaotao.zip)

**Comment by chengjun** [comment]
thank u for ur sharing of your personal final project.
