### ISSUE TITLE
王雪-18210130089-个人作业

### ISSUE THREAD

**Issue by MinnieWX** [computational-class/cjc2016#119]
#  第一次作业
- 姓名：王雪
- 学号：18210130089
- 网页：https://minniewx.github.io/

[王雪_第一次作业.html.zip](https://github.com/computational-class/cjc/files/3265539/_.html.zip)

**Comment by MinnieWX** [comment]
# 第二次作业
- 姓名：王雪
- 学号：18210130089
[王雪_第二次作业.html.zip](https://github.com/computational-class/cjc/files/3268755/_.html.zip)

**Comment by MinnieWX** [comment]
# 第三次作业
- 姓名：王雪
- 学号：18210130089
[王雪_第三次作业.html.zip](https://github.com/computational-class/cjc/files/3286740/_.html.zip)

**Comment by MinnieWX** [comment]
# 第五次作业
- 姓名：王雪
- 学号：18210130089
[王雪_第五次作业.zip](https://github.com/computational-class/cjc/files/3290723/_.zip)

**Comment by MinnieWX** [comment]
# 第四次作业
- 姓名：王雪
- 学号：18210130089
[王雪_第四次作业.html.zip](https://github.com/computational-class/cjc/files/3292973/_.html.zip)

**Comment by MinnieWX** [comment]
# 第六次作业
- 姓名：王雪
- 学号：18210130089
[王雪_第六次作业.html.zip](https://github.com/computational-class/cjc/files/3292976/_.html.zip)

**Comment by MinnieWX** [comment]
# 第七次作业
- 姓名：王雪
- 学号：18210130089
[王雪_第七次作业.zip](https://github.com/computational-class/cjc/files/3292977/_.zip)

**Comment by MinnieWX** [comment]
# 第八次作业
- 姓名：王雪
- 学号：18210130089
[王雪_第八次作业.html.zip](https://github.com/computational-class/cjc/files/3309398/_.html.zip)

**Comment by MinnieWX** [comment]
# 期末个人作业
- 姓名：王雪
- 学号：18210130089
[计算机新闻传播学期末个人作业——王雪 18210130089.html.zip](https://github.com/computational-class/cjc/files/3414406/18210130089.html.zip)

**Comment by chengjun** [comment]
thank u for sharing your personal research project.

**Comment by chengjun** [comment]
> # 期末个人作业
> * 姓名：王雪
> * 学号：18210130089
>   [计算**机**新闻传播学期末个人作业——王雪 18210130089.html.zip](https://github.com/computational-class/cjc/files/3414406/18210130089.html.zip)

没有机 ：）
