### ISSUE TITLE
Guanying LI

### ISSUE THREAD

**Issue by guanyingli** [computational-class/cjc2016#120]
# 第一次作业

- 名字: 李冠颖
- 学号: BH5339
- 个人网站: https://guanyingli.github.io/

[gyliexercise.html.zip](https://github.com/computational-class/cjc/files/3265543/gyliexercise.html.zip)

**Comment by guanyingli** [comment]
# 第二次作业

[第二次作业-李冠颖.zip](https://github.com/computational-class/cjc/files/3268679/-.zip)

**Comment by guanyingli** [comment]
# 第三次作业

[第三次作业.zip](https://github.com/computational-class/cjc/files/3289274/default.zip)

**Comment by guanyingli** [comment]
# 第四次作业
[第四次作业.zip](https://github.com/computational-class/cjc/files/3291225/default.zip)

**Comment by chengjun** [comment]
hi Guanying, thank u a lot for ur generous contribution to this class. Enjoy your research and have a good semester.

**Comment by guanyingli** [comment]
Dear Professor Wang,

Thanks so much for your class. It was really impressive and very helpful to me.

Thanks.

Best Wishes,
Guanying

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
