### ISSUE TITLE
范雅晨 18210130052

### ISSUE THREAD

**Issue by cc828** [computational-class/cjc2016#122]
#第一次作业
-Yachen Fan
-个人网页：https://cc828.github.io/
-编程作业：
[Yachen Fan 第一次作业.zip](https://github.com/computational-class/cjc/files/3265572/Yachen.Fan.zip)

**Comment by cc828** [comment]
#第二次作业
-Yachen Fan
-学号：18210130052
[范雅晨 18210130052.zip](https://github.com/computational-class/cjc/files/3268467/18210130052.zip)

**Comment by cc828** [comment]
#第三次作业 泰坦尼克号的预测分析
-Yachen Fan
-学号：18210130052
[范雅晨 第三次作业.zip](https://github.com/computational-class/cjc/files/3277066/default.zip)

**Comment by cc828** [comment]
#第四次作业 sklearn分类器+情感分析
-Yachen Fan
-学号：18210130052
[范雅晨 18210130052.zip](https://github.com/computational-class/cjc/files/3290280/18210130052.zip)

**Comment by cc828** [comment]
#第四次作业 sklearn分类器+情感分析
-Yachen Fan
-学号：18210130052
[范雅晨 18210130052.zip](https://github.com/computational-class/cjc/files/3290387/18210130052.zip)

**Comment by cc828** [comment]
#第五次作业
-Yachen Fan
-学号：18210130052
[作业（4 6 7）.zip](https://github.com/computational-class/cjc/files/3292942/4.6.7.zip)

**Comment by cc828** [comment]
#第六次作业 网络节点分析
-Yachen Fan
-学号：18210130052
[作业六 范雅晨 18210130052.zip](https://github.com/computational-class/cjc/files/3294122/18210130052.zip)

**Comment by cc828** [comment]
#第六次作业 网络节点分析
-Yachen Fan
-学号：18210130052
[范雅晨 18210130052 作业六.zip](https://github.com/computational-class/cjc/files/3294134/18210130052.zip)

**Comment by cc828** [comment]
#期末个人作业 Fake News
-Yachen Fan
-学号：18210130052
[计算传播个人作业-范雅晨.zip](https://github.com/computational-class/cjc/files/3417158/-.zip)

**Comment by chengjun** [comment]
thank u for sharing your personal research project.
