### ISSUE TITLE
请点击new issue发帖提问

### ISSUE THREAD

**Issue by chengjun** [computational-class/cjc2016#35]
使用这个方法，可以便于大家查询问题。
- 提问之前先搜索
- 软件提示出错要给出代码和出错提示两部分内容。

常见问题和解答见：

http://nbviewer.jupyter.org/github/computational-class/cjc2016/blob/gh-pages/slides/0.common_questions.slides.html#/

这里可以贴代码

```
for i in range(10):
    print i
```

**Comment by Oranni** [comment]
老师好~我这边的问题是：
http://mp.weixin.qq.com/profile?src=3&timestamp=1464169161&ver=1&signature=ZdyhV0hBgvQjTwQwq5-6NK5hujUCFRYP3lZ2MRKVslHN8DuffzOIfhWgD5sMEqcPDGSnJoGOCkBvlbOwIWwvCQ==
这个网页里面的很多class我都找不到。我用find_all列出所有class发现里面的很多class也就是一个一个的文章的上一级title都扒不出来。然后就没有办法抓取每个文章class里面的URL。
希望老师解答一下~~3Q~
对哒，老师尽快解答哈~~要交作业。。3Q老师！！！~XDDD

**Comment by chengjun** [comment]
@Oranni 举一个栗子🌰，记得给出代码

**Comment by Oranni** [comment]
`import urllib2
from bs4 import BeautifulSoup`
`url = 'http://mp.weixin.qq.com/profile?src=3&timestamp=1464169161&ver=1&signature=ZdyhV0hBgvQjTwQwq5-6NK5hujUCFRYP3lZ2MRKVslHN8DuffzOIfhWgD5sMEqcPDGSnJoGOCkBvlbOwIWwvCQ=='
content = urllib2.urlopen(url).read()
soup = BeautifulSoup(content, 'html.parser')`
`print soup.div`
`brief_info=soup.find_all('div',{'class','profile_desc_value'})`——显示[]空的列表

**Comment by chengjun** [comment]
[testWechat.ipynb.zip](https://github.com/computational-class/cjc2016/files/282112/testWechat.ipynb.zip)

@Oranni 我打印出来有东西，见附件。

**Comment by Oranni** [comment]
收到，我没有逐一打印，我再看看怎么扒文章的list  ，非常谢谢老师~

祝好，
刘妮
