### ISSUE TITLE
王希 17210130097 作业1

### ISSUE THREAD

**Issue by yyxxabcdefg** [computational-class/cjc2016#85]
[WangXi17210130097  homework1.zip](https://github.com/computational-class/cjc/files/1955213/WangXi17210130097.homework1.zip)

**Comment by yyxxabcdefg** [comment]
[homework2.csv.zip](https://github.com/computational-class/cjc/files/2159947/homework2.csv.zip)
[homework2.ipynb.zip](https://github.com/computational-class/cjc/files/2159950/homework2.ipynb.zip)

**Comment by yyxxabcdefg** [comment]
[homework3.ipynb.zip](https://github.com/computational-class/cjc/files/2159954/homework3.ipynb.zip)

**Comment by yyxxabcdefg** [comment]
[homework4.ipynb.zip](https://github.com/computational-class/cjc/files/2159955/homework4.ipynb.zip)
[homework5.ipynb.zip](https://github.com/computational-class/cjc/files/2159957/homework5.ipynb.zip)

**Comment by chengjun** [comment]
where are the 6th, 7th, and 8th homework ?
