### ISSUE TITLE
唐昕宁-17210130090-作业

### ISSUE THREAD

**Issue by txn0121** [computational-class/cjc2016#86]
作业一
[Homework1_TangXinning.zip](https://github.com/computational-class/cjc/files/1955463/Homework1_TangXinning.zip)

**Comment by txn0121** [comment]
作业三（1）：天涯论坛帖子分析
[Homework3-TangXinning-tianya.zip](https://github.com/computational-class/cjc/files/1958695/Homework3-TangXinning-tianya.zip)

作业三（2）：泰坦尼克-KNN模型分析
[Homework3-TangXinning-tatanic-knn.zip](https://github.com/computational-class/cjc/files/1960908/Homework3-TangXinning-tatanic-knn.zip)

**Comment by txn0121** [comment]
作业二：TwitterRAW提取
[Homework2-TangXinning-tweet.zip](https://github.com/computational-class/cjc/files/1976347/Homework2-TangXinning-tweet.zip)

**Comment by txn0121** [comment]
作业四：政府工作报告文本挖掘
[Homework4_TangXinning_gov_textmining.zip](https://github.com/computational-class/cjc/files/1976443/Homework4_TangXinning_gov_textmining.zip)

**Comment by txn0121** [comment]
作为五（1）：sklearn分类器
[Homework5_TangXinning_sklearn_tweet-negative2.zip](https://github.com/computational-class/cjc/files/1977433/Homework5_TangXinning_sklearn_tweet-negative2.zip)

**Comment by txn0121** [comment]
作业五（2）：推特情感分析(*^▽^*)/(ಥ﹏ಥ)
[Homework5_TangXinning_推特情感分析.zip](https://github.com/computational-class/cjc/files/2092446/Homework5_TangXinning_.zip)

**Comment by txn0121** [comment]
作业六：graphlab主题模型
[Homework6_TangXinning_graphlab主题模型-02.zip](https://github.com/computational-class/cjc/files/2094833/Homework6_TangXinning_graphlab.-02.zip)

**Comment by txn0121** [comment]
作业七（1）：UserCF和ItemCF的python3代码
[Homework7_TangXinning_UserCF+ItemCF_Python3.zip](https://github.com/computational-class/cjc/files/2096478/Homework7_TangXinning_UserCF.ItemCF_Python3.zip)

**Comment by txn0121** [comment]
作业七（2）：使用graphlab作电影推荐
[Homework7_TangXinning_使用graphlab作电影推荐.zip](https://github.com/computational-class/cjc/files/2096536/Homework7_TangXinning_.graphlab.zip)

**Comment by txn0121** [comment]
作业八：Networkx
[Homework8_TangXinning_networkx.zip](https://github.com/computational-class/cjc/files/2110142/Homework8_TangXinning_networkx.zip)

**Comment by txn0121** [comment]
期末作业：个人版
[Finalwork_TangXinning.zip](https://github.com/computational-class/cjc/files/2159735/Finalwork_TangXinning.zip)

**Comment by chengjun** [comment]
Great Job!
