### ISSUE TITLE
Fang Yuan’s Homework 

### ISSUE THREAD

**Issue by yuan-fang1** [computational-class/cjc2016#88]
## Homework 1

[方圆 - 17210130046 - HW1.zip](https://github.com/computational-class/cjc/files/1955603/-.17210130046.-.HW1.zip)

作业一 from 方圆 17210130046
: )

**Comment by yuan-fang1** [comment]
## Homework 2

[方圆 - 17210130046 - HW2.zip](https://github.com/computational-class/cjc/files/1958571/-.17210130046.-.HW2.zip)

作业二 from 方圆 17210130046
XD

**Comment by yuan-fang1** [comment]
## Homework 3

[方圆 - 17210130046 - HW3.zip](https://github.com/computational-class/cjc/files/1967742/-.17210130046.-.HW3.zip)

作业三 from 方圆 17210130046
<(￣︶￣)>

**Comment by yuan-fang1** [comment]
## Homework 4

[方圆 - 17210130046 - HW4.zip](https://github.com/computational-class/cjc/files/1991466/-.17210130046.-.HW4.zip)

作业四 from 方圆 17210130046
；）

**Comment by yuan-fang1** [comment]
## Homework 5

[方圆 - 17210130046 - HW5.zip](https://github.com/computational-class/cjc/files/1991471/-.17210130046.-.HW5.zip)

作业五 from 方圆 17210130046
（・∀・）

**Comment by yuan-fang1** [comment]
## Homework 6

[方圆 - 17210130046 - HW6.zip](https://github.com/computational-class/cjc/files/1992342/-.17210130046.-.HW6.zip)

作业六 from 方圆 17210130046
(^_^)v

**Comment by yuan-fang1** [comment]
## Homework 7

[方圆 - 17210130046 - HW7.zip](https://github.com/computational-class/cjc/files/1992375/-.17210130046.-.HW7.zip)

作业七 from 方圆 17210130046
(((o(*ﾟ▽ﾟ*)o)))

**Comment by yuan-fang1** [comment]
## Homework 8

[方圆 - 17210130046 - HW8.zip](https://github.com/computational-class/cjc/files/2108065/-.17210130046.-.HW8.zip)

作业八 from 方圆 17210130046
(*^▽^*)

**Comment by yuan-fang1** [comment]
## 个人附件作业

[方圆 - 17210130046 - Final Group Project For Individuals.zip](https://github.com/computational-class/cjc/files/2109141/-.17210130046.-.Final.Group.Project.For.Individuals.zip)

个人附加作业 from 方圆 17210130046
٩(๑>◡<๑)۶

**Comment by chengjun** [comment]
GOOD JOB.
