### ISSUE TITLE
伍音璇-作业-17210130103

### ISSUE THREAD

**Issue by wuyinxuan** [computational-class/cjc2016#90]
[伍音璇-第一次作业.html.zip](https://github.com/computational-class/cjc/files/1955895/-.html.zip)

**Comment by wuyinxuan** [comment]
[伍音璇-第二次作业.html.zip](https://github.com/computational-class/cjc/files/2153265/-.html.zip)

**Comment by wuyinxuan** [comment]
[伍音璇-第三次作业.html.zip](https://github.com/computational-class/cjc/files/2158921/-.html.zip)
天涯论坛数据的统计分析部分
泰坦尼克号数据的机器学习部分

**Comment by wuyinxuan** [comment]
[伍音璇-第四次作业.html.zip](https://github.com/computational-class/cjc/files/2160797/-.html.zip)
政府工作报告文本挖掘

**Comment by wuyinxuan** [comment]
[伍音璇-第六次作业.html.zip](https://github.com/computational-class/cjc/files/2160946/-.html.zip)
使用graphlab进行主题模型分析

**Comment by wuyinxuan** [comment]
[伍音璇-第五次作业.html.zip](https://github.com/computational-class/cjc/files/2161024/-.html.zip)
使用另外一种sklearn的分类器来对tweet_negative2进行情感分析

**Comment by wuyinxuan** [comment]
[伍音璇-第七次作业.html.zip](https://github.com/computational-class/cjc/files/2161230/-.html.zip)
使用graphlab对于音乐数据或电影数据构建推荐系统

**Comment by chengjun** [comment]
there is no 8th homework?
