### ISSUE TITLE
尹航 作业汇总

### ISSUE THREAD

**Issue by mochamochachan** [computational-class/cjc2016#94]
尹航 17210130115
很高兴和大家共同学习进步~
[homework1.zip](https://github.com/computational-class/cjc/files/1957340/homework1.zip)

**Comment by mochamochachan** [comment]
尹航 作业2
[Homework2.zip](https://github.com/computational-class/cjc/files/1958412/Homework2.zip)

**Comment by Olli1994** [comment]
好的

**Comment by mochamochachan** [comment]
尹航 作业3
[Homework3.zip](https://github.com/computational-class/cjc/files/1958847/Homework3.zip)

**Comment by mochamochachan** [comment]
尹航 作业5
[Homework5.zip](https://github.com/computational-class/cjc/files/1975505/Homework5.zip)

**Comment by mochamochachan** [comment]
尹航 作业6
[homework6.zip](https://github.com/computational-class/cjc/files/1975682/homework6.zip)

**Comment by mochamochachan** [comment]
尹航 作业4
换头像了！开心！！
[homework4.zip](https://github.com/computational-class/cjc/files/1976215/homework4.zip)

**Comment by mochamochachan** [comment]
尹航 作业7
[Homework7.zip](https://github.com/computational-class/cjc/files/1976442/Homework7.zip)

**Comment by mochamochachan** [comment]
尹航 作业8
[homework8.zip](https://github.com/computational-class/cjc/files/1977424/homework8.zip)
